/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.Servlet;

import org.apache.struts2.ServletActionContext;

import domain.Collection;
import domain.Post;
import domain.User;
import service.inter.CollectionServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 02-03-2017
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class CollectionAction{
	
	@Resource
	CollectionServiceInter collectionServiceInter;

	public void setCollectionServiceInter(
			CollectionServiceInter collectionServiceInter) {
		this.collectionServiceInter = collectionServiceInter;
	}
	
	public String collect() {
		Collection c=new Collection();
		c.setPost((Post) ServletActionContext.getRequest().getSession().getAttribute("post"));
		c.setUser((User) ServletActionContext.getRequest().getSession().getAttribute("user"));
		c.setTime(new Date());
		collectionServiceInter.add(c);
		return "collect";
	}
	
	public String delete() {
		Collection c=new Collection();
		int userId=((User)ServletActionContext.getRequest().getSession().getAttribute("user")).getId();
		int postId=Integer.parseInt(ServletActionContext.getRequest().getParameter("postId"));
		c=collectionServiceInter.getByUserPost(userId, postId);
		collectionServiceInter.delete(c);
		return "delete";
	}

	
//	public ActionForward add(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		// TODO Auto-generated method stub
//		CollectionForm cf=(CollectionForm) form;
//		Collection c=new Collection();
//		c.setUser((User) request.getSession().getAttribute("user"));
//		c.setPost((Post) request.getSession().getAttribute("post"));
//		c.setComment(cf.getComment());
//		c.setTime(new Date());
//		collectionServiceInter.add(c);
//		return mapping.findForward("ok");
//	}
}