/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;
import javax.annotation.Resource;
import service.inter.CollectionServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 02-03-2017
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class CollectionAction{
	
	@Resource
	CollectionServiceInter collectionServiceInter;

	public void setCollectionServiceInter(
			CollectionServiceInter collectionServiceInter) {
		this.collectionServiceInter = collectionServiceInter;
	}
	
//	public ActionForward add(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		// TODO Auto-generated method stub
//		CollectionForm cf=(CollectionForm) form;
//		Collection c=new Collection();
//		c.setUser((User) request.getSession().getAttribute("user"));
//		c.setPost((Post) request.getSession().getAttribute("post"));
//		c.setComment(cf.getComment());
//		c.setTime(new Date());
//		collectionServiceInter.add(c);
//		return mapping.findForward("ok");
//	}
}