/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;

import java.util.Date;

import javax.annotation.Resource;
import domain.Comment;
import domain.Post;
import domain.User;
import service.inter.CommentServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 02-01-2017
 * 
 * XDoclet definition:
 * @struts.action path="/comment" name="commentForm" parameter="flag" scope="request"
 */
public class CommentAction{
	
	@Resource
	CommentServiceInter commentServiceInter;
	
//	public ActionForward publish(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		CommentForm commentForm = (CommentForm) form;// TODO Auto-generated method stub
//		Comment comment=new Comment();
//		comment.setUser((User) request.getSession().getAttribute("user"));
//		comment.setPost((Post) request.getSession().getAttribute("post"));
//		comment.setContent(commentForm.getContent());
//		comment.setTime(new Date());
//		commentServiceInter.add(comment);
//		return mapping.findForward("published");
//	}
}