/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.servlet.Servlet;

import org.apache.commons.io.FileUtils;
import org.apache.struts2.ServletActionContext;
import domain.Comment;
import domain.Post;
import domain.User;
import service.imp.PostService;
import service.inter.CommentServiceInter;
import service.inter.PostServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 01-24-2017
 * 
 * XDoclet definition:
 * @struts.action path="/post" name="postForm" parameter="flag" scope="request"
 */
public class PostAction{
	
	private String title;
	private String userName;
	private String content;
	private Date time;
	private File musicFile;
	private String musicFileFileName;
	private String type;					//type和musicName决定了音乐文件的服务器路径
	private InputStream downloadFile;
	
	@Resource
	PostServiceInter postServiceInter;
	@Resource
	CommentServiceInter commentServiceInter;
	
	public String read() {
		int id=Integer.parseInt(ServletActionContext.getRequest().getParameter("id"));
//		int id=32;
		Post p=(Post) postServiceInter.getById(id);
		ServletActionContext.getRequest().getSession().setAttribute("post", p);
		List<Comment> comments=commentServiceInter.getByPostIdcodec(id);
		ServletActionContext.getRequest().getSession().setAttribute("comments", comments);
//		this.title=p.getTitle();
//		this.userName=p.getUser().getName();
//		this.content=p.getContent();
//		this.time=p.getTime();
		return "post";
	}
	
	public String download()
	{
//		String path=ServletActionContext.getServletContext().getRealPath("/")+"/WEB-INF/resource/";
		String path="E:/music/";
		String type=(String) ServletActionContext.getRequest().getAttribute("type");
		String fileName=(String) ServletActionContext.getRequest().getAttribute("fileName");
		File file=new File(path+type+"/"+fileName);
		try {
			downloadFile=new FileInputStream(file);
		}catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
//	    downloadFile=ServletActionContext.getServletContext().getResourceAsStream("../resource/waltz.mp3");
	    System.out.println(downloadFile);
	    return "download";
	}
	
//	public ActionForward read(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		// TODO Auto-generated method stub
//		
//		PostForm postForm=(PostForm) form;
//		int postId=postForm.getId();
//		Post post=(Post) postServiceInter.getById(postId);
//		List<Comment> comments=commentServiceInter.getByPostId(postId);
//		request.getSession().setAttribute("post", post);
//		request.getSession().setAttribute("comments", comments);
//		return mapping.findForward("readPost");
//	}
	
//	public ActionForward publish(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		// TODO Auto-generated method stub
//		
//		PostForm postForm = (PostForm) form;
//		Post p=new Post();
//		p.setTitle(postForm.getTitle());
//		p.setUser((User) request.getSession().getAttribute("user"));
//		p.setContent(postForm.getContent());
//		p.setTime(new java.util.Date());
//		postServiceInter.add(p);
//		return mapping.findForward("published");
//	}
	
	public String publish() {
		if(this.musicFile==null)return "error";
		Post p=new Post();
		p.setTitle(this.title);
		User u=(User) ServletActionContext.getRequest().getSession().getAttribute("user");
		p.setUser(u);
		p.setContent(this.content);
		p.setTime(new Date());
		p.setMusicName(this.musicFileFileName);
//		p.setType(this.type);
		p.setType("classic");
		postServiceInter.add(p);
		
//		String path=ServletActionContext.getServletContext().getRealPath("/")+"/WEB-INF/resource/music/classic/";
		String path="E:/music";
		if(postServiceInter.upLoadFile(this.musicFile, this.musicFileFileName, path)==false)
			return "error";
		
		return "myself";
	}

	//���⣬�����Ѿ���ã������ļ��Ѿ��ϴ����������ô�����
	public String publish1() {
		System.out.println(this.musicFileFileName);
		System.out.println(this.musicFile);
		if(this.musicFile==null)return "error";
		User u=new User();
		u.setId(1);
		
		Post p=new Post();
		p.setTitle(this.title);
//		p.setTitle("����");
		p.setUser(u);
//		p.setUser((User)ServletActionContext.getRequest().getSession().getAttribute("user"));
//		System.out.println(p.getUser().getId());
//		p.setContent("fe");
		p.setContent(this.content);
		p.setTime(new Date());
		p.setMusicName(this.musicFileFileName);
//		type=(String)ServletActionContext.getRequest().getSession().getAttribute("postType");
		p.setType("classic");
		postServiceInter.add(p);
		
		String path=ServletActionContext.getServletContext().getRealPath("/")+"/WEB-INF/resource/music/classic/";
		
		if(postServiceInter.upLoadFile(this.musicFile, this.musicFileFileName, path)==false)
			return "error";
		
		return "success";
	}

	public PostServiceInter getPostServiceInter() {
		return postServiceInter;
	}

	public void setPostServiceInter(PostServiceInter postServiceInter) {
		this.postServiceInter = postServiceInter;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public File getMusicFile() {
		return musicFile;
	}

	public void setMusicFile(File musicFile) {
		this.musicFile = musicFile;
	}

	public String getMusicFileFileName() {
		return musicFileFileName;
	}

	public void setMusicFileFileName(String musicFileFileName) {
		this.musicFileFileName = musicFileFileName;
	}

	public InputStream getDownloadFile() {
		return downloadFile;
	}

	public void setDownloadFile(InputStream downloadFile) {
		this.downloadFile = downloadFile;
	}
}