/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package action;

import java.io.File;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;

import org.apache.commons.io.FileUtils;
import org.apache.struts2.ServletActionContext;
import domain.Comment;
import domain.Post;
import domain.User;
import service.imp.PostService;
import service.inter.CommentServiceInter;
import service.inter.PostServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 01-24-2017
 * 
 * XDoclet definition:
 * @struts.action path="/post" name="postForm" parameter="flag" scope="request"
 */
public class PostAction{
	
	private String title;
	private String userName;
	private String content;
	private Date time;
	private String musicName;
	private File musicFile;
	private String musicFileFileName;
	private String type;
	
	@Resource(name="postService")
	PostServiceInter postServiceInter;
	@Resource
	CommentServiceInter commentServiceInter;
	
//	public ActionForward read(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		// TODO Auto-generated method stub
//		
//		PostForm postForm=(PostForm) form;
//		int postId=postForm.getId();
//		Post post=(Post) postServiceInter.getById(postId);
//		List<Comment> comments=commentServiceInter.getByPostId(postId);
//		request.getSession().setAttribute("post", post);
//		request.getSession().setAttribute("comments", comments);
//		return mapping.findForward("readPost");
//	}
	
//	public ActionForward publish(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		// TODO Auto-generated method stub
//		
//		PostForm postForm = (PostForm) form;
//		Post p=new Post();
//		p.setTitle(postForm.getTitle());
//		p.setUser((User) request.getSession().getAttribute("user"));
//		p.setContent(postForm.getContent());
//		p.setTime(new java.util.Date());
//		postServiceInter.add(p);
//		return mapping.findForward("published");
//	}

	//标题，作者已经填好，音乐文件已经上传，其他的用代码获得
	public String publish() {
		System.out.println(this.musicFileFileName);
		System.out.println(this.musicFile);
		if(this.musicFile==null)return "error";
		User u=new User();
		u.setId(1);
		
		Post p=new Post();
		p.setTitle(this.title);
//		p.setTitle("哈哈");
		p.setUser(u);
//		p.setUser((User)ServletActionContext.getRequest().getSession().getAttribute("user"));
//		System.out.println(p.getUser().getId());
//		p.setContent("fe");
		p.setContent(this.content);
		p.setTime(new Date());
		p.setMusicName(this.musicFileFileName);
//		type=(String)ServletActionContext.getRequest().getSession().getAttribute("postType");
		p.setType("classic");
		postServiceInter.add(p);
		
		String path=ServletActionContext.getServletContext().getRealPath("/")+"/WEB-INF/resource/music/classic/";
		
		
		if(postServiceInter.upLoadFile(this.musicFile, this.musicFileFileName, path)==false)
			return "error";
		
		return "success";
	}

	public PostServiceInter getPostServiceInter() {
		return postServiceInter;
	}

	public void setPostServiceInter(PostServiceInter postServiceInter) {
		this.postServiceInter = postServiceInter;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getMusicName() {
		return musicName;
	}

	public void setMusicName(String musicName) {
		this.musicName = musicName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public File getMusicFile() {
		return musicFile;
	}

	public void setMusicFile(File musicFile) {
		this.musicFile = musicFile;
	}

	public String getMusicFileFileName() {
		return musicFileFileName;
	}

	public void setMusicFileFileName(String musicFileFileName) {
		this.musicFileFileName = musicFileFileName;
	}
}